### ISSUE TITLE
Отсутствие таблицы services в mysql при построении дерева

### ISSUE THREAD

**Issue by VitalyWhite** [DRVTiny/Druid#1]
Появляется подобная ошибка во время попытки задать дочерний сервис.
Server version: 10.1.43-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

root@zabbix-test:~/Druid/engine# ./tools/itsvc create 'Test_child' -p 1
DBD::mysql::st execute failed: Duplicate entry '1' for key 'PRIMARY' at /home/user/Druid/engine/tools/../lib/Monitoring/Zabipi/ITServices.pm line 381.
{
   "error" : "DBD::mysql::st execute failed: Duplicate entry '1' for key 'PRIMARY' at /home/user/Druid/engine/tools/../lib/Monitoring/Zabipi/ITServices.pm line 381.\n"
}

![mysql](https://user-images.githubusercontent.com/37037198/69432887-9adb6800-0d4b-11ea-94e1-98e13ff7bfdd.jpg)

**Comment by DRVTiny** [comment]
Yeah, that a pretty wonderful bug! :)
OK, resolved by this commit: https://github.com/DRVTiny/Druid/commit/56b88c243cfe2acd6c36d3dd2428813114c00c98
